name: to_do_app
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  syncfusion_flutter_calendar: ^21.2.10

  # firebase integration
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1

  # slidable
  flutter_slidable: ^3.0.0

  # state management
  provider: ^6.0.5
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true